version: "3"
services:
  nginx_proxy:
    image: nginx:1.25.3
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./templates:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./log:/log/
    restart: always

networks:
  default:
    name: nginx_proxy
    external: true
