version: "3"
services:
  nginx_proxy:
    image: nginx:1.25.3
    ##    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      #      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./templates:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./log:/log/
#      - nginx_volume:/data/:ro
#      - static_volume:/opt/my_app/static/
#      - media_volume:/opt/my_app/media/
    restart: always
#    networks:
#      - nginx_proxy

networks:
  default:
    name: nginx_proxy
    external: true

#volumes:
#  static_volume:
#    external: true
#  media_volume:
#    external: true
#  nginx_volume:
#    external: true

